version: "3"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.3-30.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "389:389"
    environment:
      STORAGE_DIR: /storage/fs1
    volumes:
      - ./dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - ./dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
    restart: always
  db:
    image: dcm4che/postgres-dcm4chee:15.2-30 #imagem contem dezenas de create, update e alter tables
    logging:                                 #que criam o ambiente para funcionamento do dcm
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: pacsdb_g2i
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: pacs
    volumes:
      - ./etc/localtime:/etc/localtime:ro
      - ./etc/timezone:/etc/timezone:ro
      - ./dcm4chee-arc/db:/var/lib/postgresql/data #voluma que armazena os dados do banco
    restart: always
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.30.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "8888:8080"
      - "8444:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    environment:
      POSTGRES_DB: pacsdb_g2i
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: pacs
      WILDFLY_CHOWN: /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432 #bate na conexão do banco, ele nao resolve ip do host: 192.168.15.22
      # KEYSTORE: /opt/wildfly/standalone/configuration/keystores/keystore.pkcs12
      # KEYSTORE_PASSWORD: '051390'
    depends_on:
      - ldap
      - db
    volumes:
      - ./etc/localtime:/etc/localtime:ro
      - ./etc/timezone:/etc/timezone:ro
      - ./dcm4chee-arc/wildfly:/opt/wildfly/standalone #armazena dados de confg do wild
      - ./dcm4chee-arc/storage:/storage # armazena os dados recebidos do dicom la na fs1/ano/mes/dia/arquivo
      # - ./path/keystore.pkcs12:/opt/wildfly/standalone/configuration/keystores/keystore.pkcs12
    restart: always
  ohif-viewer-container:
    image: ohif/app:v3.7.0-beta.62
    ports:
      - '3004:8081'
    environment:
      # SSL_PORT: 4443
      PORT: 8081
      APP_CONFIG: >
        window.config = {
          routerBasename: '/',
          extensions: [],
          modes: [],
          customizationService: {},
          showStudyList: true,
          maxNumberOfWebWorkers: 3,
          omitQuotationForMultipartRequest: true,
          showWarningMessageForCrossOrigin: true,
          showCPUFallbackMessage: true,
          showLoadingIndicator: true,
          strictZSpacingForVolumeViewport: true,
          maxNumRequests: {
            interaction: 100,
            thumbnail: 75,
            prefetch: 25,
          },
          defaultDataSourceName: 'dicomweb',
          dataSources: [
            {
              friendlyName: 'dcmjs DICOMWeb Server',
              namespace: '@ohif/extension-default.dataSourcesModule.dicomweb',
              sourceName: 'dicomweb',
              configuration: {
                name: 'aws',
                wadoUriRoot: 'http://localhost:8888/dcm4chee-arc/aets/DCM4CHEE/wado',
                qidoRoot: 'http://localhost:8888/dcm4chee-arc/aets/DCM4CHEE/rs',
                wadoRoot: 'http://localhost:8888/dcm4chee-arc/aets/DCM4CHEE/rs',
                qidoSupportsIncludeField: false,
                supportsReject: false,
                imageRendering: 'wadors',
                thumbnailRendering: 'wadors',
                enableStudyLazyLoad: true,
                supportsFuzzyMatching: false,
                supportsWildcard: true,
                staticWado: true,
                singlepart: 'bulkdata,video',
                bulkDataURI: {
                  enabled: true,
                  relativeResolution: 'studies',
                },
              },
            },
            {
              friendlyName: 'dicomweb delegating proxy',
              namespace: '@ohif/extension-default.dataSourcesModule.dicomwebproxy',
              sourceName: 'dicomwebproxy',
              configuration: {
                name: 'dicomwebproxy',
              },
            },
            {
              friendlyName: 'dicom json',
              namespace: '@ohif/extension-default.dataSourcesModule.dicomjson',
              sourceName: 'dicomjson',
              configuration: {
                name: 'json',
              },
            },
            {
              friendlyName: 'dicom local',
              namespace: '@ohif/extension-default.dataSourcesModule.dicomlocal',
              sourceName: 'dicomlocal',
              configuration: {},
            },
          ],
          httpErrorHandler: error => {
            console.warn(error.status);
            console.warn('test, navigate to https://ohif.org/');
          },
          hotkeys: [
            {
              commandName: 'incrementActiveViewport',
              label: 'Next Viewport',
              keys: ['right'],
            },
            {
              commandName: 'decrementActiveViewport',
              label: 'Previous Viewport',
              keys: ['left'],
            },
            { commandName: 'rotateViewportCW', label: 'Rotate Right', keys: ['r'] },
            { commandName: 'rotateViewportCCW', label: 'Rotate Left', keys: ['l'] },
            { commandName: 'invertViewport', label: 'Invert', keys: ['i'] },
            {
              commandName: 'flipViewportHorizontal',
              label: 'Flip Horizontally',
              keys: ['h'],
            },
            {
              commandName: 'flipViewportVertical',
              label: 'Flip Vertically',
              keys: ['v'],
            },
            { commandName: 'scaleUpViewport', label: 'Zoom In', keys: ['+'] },
            { commandName: 'scaleDownViewport', label: 'Zoom Out', keys: ['-'] },
            { commandName: 'fitViewportToWindow', label: 'Zoom to Fit', keys: ['='] },
            { commandName: 'resetViewport', label: 'Reset', keys: ['space'] },
            { commandName: 'nextImage', label: 'Next Image', keys: ['down'] },
            { commandName: 'previousImage', label: 'Previous Image', keys: ['up'] },
            // {
            //   commandName: 'previousViewportDisplaySet',
            //   label: 'Previous Series',
            //   keys: ['pagedown'],
            // },
            // {
            //   commandName: 'nextViewportDisplaySet',
            //   label: 'Next Series',
            //   keys: ['pageup'],
            // },
            {
              commandName: 'setToolActive',
              commandOptions: { toolName: 'Zoom' },
              label: 'Zoom',
              keys: ['z'],
            },
            // ~ Window level presets
            {
              commandName: 'windowLevelPreset1',
              label: 'W/L Preset 1',
              keys: ['1'],
            },
            {
              commandName: 'windowLevelPreset2',
              label: 'W/L Preset 2',
              keys: ['2'],
            },
            {
              commandName: 'windowLevelPreset3',
              label: 'W/L Preset 3',
              keys: ['3'],
            },
            {
              commandName: 'windowLevelPreset4',
              label: 'W/L Preset 4',
              keys: ['4'],
            },
            {
              commandName: 'windowLevelPreset5',
              label: 'W/L Preset 5',
              keys: ['5'],
            },
            {
              commandName: 'windowLevelPreset6',
              label: 'W/L Preset 6',
              keys: ['6'],
            },
            {
              commandName: 'windowLevelPreset7',
              label: 'W/L Preset 7',
              keys: ['7'],
            },
            {
              commandName: 'windowLevelPreset8',
              label: 'W/L Preset 8',
              keys: ['8'],
            },
            {
              commandName: 'windowLevelPreset9',
              label: 'W/L Preset 9',
              keys: ['9'],
            },
          ],
        };
    volumes:
      # - ./path/server.crt:/etc/ssl/certs/ssl-certificate.crt:ro
      # - ./path/server.key:/etc/ssl/private/ssl-private-key.key:ro
      - ./config.js:/usr/share/nginx/html/default.js:ro
    restart: always